### PR TITLE
Adds new test to self-test for get_url over HTTPS

### PR DESCRIPTION
**Pull request by hollie**
Adds extra test that does a POST request over HTTPS to the MisterHouse selftests.

### CODE REVIEW

**Comment by hollie** [comment]
Fails on Perl 5.08. Do we still need to support that?

**Comment by hollie** [comment]
Going to close and re-open this PR to see if the fail was due to an external reason or not.

**Comment by hplato** [comment]
This is the only outstanding pull request. I have a perl 5.8.8 machine, and the test seems to work OK for me:

# ./get_url -post 'testparameter=1' https://httpbin.org/post /tmp/get_url_post_https.txt
Retrieving (with ua) https://httpbin.org/post into /tmp/get_url_post_https.txt ... url retrieved.
# cat /tmp/get_url_post_https.txt 
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "testparameter": "1"
  }, 
  "headers": {
    "Content-Length": "15", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0"
  }, 
  "json": null, 
  "origin": "xx.xx.xx.xx", 
  "url": "https://httpbin.org/post"
}
# perl -v

This is perl, v5.8.8 built for i386-linux-thread-multi

Copyright 1987-2006, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by marcmerlin** [comment]
So, is this pull request getting backed out, or fixed and merged?

**Comment by hollie** [comment]
I suggest to drop it.

**Pull request closed without merging**
