### PR TITLE
Integration with the Google Assistant via Actions on Google Smart Home provider

### PR DESCRIPTION
**Pull request by peloy**
This allows users to integrate their MisterHouse installations with the Google Assistant via the Actions on Google (AoG) Smart Home provider. This work was announced on the misterhouse-users mailing list several months ago:

https://sourceforge.net/p/misterhouse/mailman/message/36117781/

and configuration and use have been documented on the wiki at:

https://github.com/hollie/misterhouse/wiki/Integration-With-The-Actions-on-Google-Smart-Home-Provider

I have been running this code since then with no issues and know of at least another user who is also running it with no issues.

Please let me know if you have any comments, questions, or concerns.

Cheers,

Eloy Paris.-

### CODE REVIEW

**Comment by hplato** [comment]
Thanks for the contribution Eloy!

**Comment by peloy** [comment]
Sure thing; thanks for merging the pull request!

I'm keeping an eye on the mailing list to see if anyone reports
problems... for the most part the change is safe but it does touch
http_server.pl, which everybody uses, so we have to keep an eye on
things.

Cheers,

Eloy Paris.-

**Comment by klier** [comment]
I upgraded to the latest version, Eloy, and the only change I had to make
was in my personal .mht file that has the references to the
AOGSMARTHOME_ITEMs.  I simply had to change my "type=" to all lowercase. I
had my types listed as "Switch" and "Light" and they errored out upon
load.  Everything is perfect listing them as "switch" and "light".

Brian

**Comment by peloy** [comment]
Aha, sorry about that! I guess at some point after the initial
announcement (and your subsequent set up), I went and tweaked the
AoGSmartHome_Items parsing code. I see that we now have:

    # Check that the type is a supported one
    if ($type ne 'light' && $type ne 'scene' && $type ne 'switch'
	&& $type ne 'outlet'&& $type ne 'thermostat') {
	&main::print_log("[AoGSmartHome] Invalid device type '$type'; ignoring AoG item.");
	return;
    }

I guess a case insensitive comparison would have been more appropriate here. Oh
well...

Thanks for upgrading and testing!

Cheers,

Eloy Paris.-

**Pull request merged**
