### PR TITLE
PerlTidy Code Base; Add PerlTidy Helpers

### PR DESCRIPTION
**Pull request by krkeegan**
This is the giant perltidy merge! :boom: 

The branch contains a code base on which perltidy has been run to make nice and consistent looking code.  The process required a lot more manual code edits than I had expected.  I believe everything is working, but please test this branch for me.

__A notable issue__ - Please be very careful when using the end of line `# noloop` comment.  If the line, including comment, is over 80 characters, perltidy will split up the line.  This results in the `# noloop` comment only appearing on one of the two lines, which will lead to an error.  To avoid any potential for this error the preference is now to use `# noloop=start` and `# noloop=stop` comments when contributing code.  This does NOT affect user_code which is not touched by perltidy.

The branch also contains a few new files:
- bin/perltidyall (bin/perltidyall.bat for WinOS) - A free standing script that when called will run perltidy on the entire code base.  Use this for cleaning up the code prior to a release or for cleaning up your own changes before committing them.
- bin/githook-perltidy (bin/githook-perltidy.bat for WinOS) - This script can be used to automatically install a perltidy githook on your system.  This will cause perltidy to be run ONLY on the files that have been changed during the commit process.  While a batch file is provided for WinOS support, currently the git environment cannot be made to work with the commit script.  The batch file is provided should this ever be solved.

### CODE REVIEW

**Comment by hollie** [comment]
Hey @krkeegan 

hmm, what I feared happened: in the mean time this pull request conflicts with other changes that were merged into master. 

Do we go forward with this and should I try to resolve the conflicts? Or is it better to tidy up the current master and put that in a new pull request?

Kind regards,
 Lieven.

**Comment by JaredF** [comment]
There are currently 35 files with conflicts to this pull request.  We can try to go through these one by one and manually merge the changes, but that would be pretty tedious.

One option would be to ignore the PerlTidy changes on these files, merge this pull request in, then re-run PerlTidy on the entire base which should then bring just those conflicted files up to date.

@krkeegan, I know that you've probably been pretty busy, but let us know if you have any ideas or suggestions.  Once we have something that is mergeable, let's get it in ASAP.

I've noticed that we already have some documentation that assumes this pull has been merged:  https://github.com/hollie/misterhouse/wiki/Contributing#using-perltidy-to-make-consistent-formatted-code

**Comment by hollie** [comment]
@JaredF yes, I agree with this. Let's merge the required changes ignoring the PerlTidy and re-run (and immediately commit) the PerlTidy changes.

**Comment by JaredF** [comment]
So after thinking about this a bit more, there are two more minor issues if we go with the above method:

1.  Doing this will probably cause the same issue we are seeing with this pull to happen to all of the other pull requests that are in the queue.  We should try to merge in any that are ready and just add whatever files these may change to the conflict list.  Any remaining pull requests after the big merge will then have to be rebased and merged manually by their original author.

2.  I'm not sure exactly how GitHub works when working on someone else's pull request, but I would want to make sure that @krkeegan gets the credit for this work and not have everything just show under the person that resolved the conflicts.  I know that this may not be a big deal to some, but this took a lot of work and credit should be given where it is due.

**Comment by hollie** [comment]
Hey @JaredF 

 1. Yes I agree, however I don't think it would be a problem for the few pull requests that are open. Some of them we can merge (I've asked for input form others, if there is not input I think we can merge the pull request).

 1. Github keeps track of the code. If we merge the changes to add PerlTidy support from this pull request then as far as I know @krkeegan will get the credit. If this fails, let's add his name at the relevant locations in the source code.

**Comment by hollie** [comment]
Hey @JaredF and @krkeegan 

as was rightfully mentioned in the last comment from Jared we need to give credit where credit is due. I have created a new pull request that cherry-picks the actual perltidy code that Kevin added.

This way all commits are accounted to Kevin.

Is is OK to procedeer to close this pull request and continue with the new one #555 ?

**Comment by JaredF** [comment]
Sounds great to me!  Apologies for not getting around to this sooner.

**Comment by hollie** [comment]
Closing this pull request, it is superseded by #557

**Pull request closed without merging**
