### PR TITLE
Major web interface rehaul

### PR DESCRIPTION
**Pull request by hollie**
Rehaul of the web interface. Let's make it look like it's 2015!

### CODE REVIEW

**Comment by hollie** [comment]
Just a basic question: would there be a way to give certain objects a 'nice' name to be displayed in the web interface?

The iphone interface has this (you could call $object->set_label("Nice name")).

**Comment by hollie** [comment]
I currently have no time to submit a patch, but I notice the link to the wiki still points to the wikispace wiki. Something that needs fixing (and that is possibly not only for ia7).

**Comment by hplato** [comment]
Yes, you can give things nice names using the set_label command.

**Comment by hplato** [comment]
I'll fix the wiki link, and add instructions on how to use the interface

**Comment by hollie** [comment]
Hey @hplato 

thanks for the feedback and the fix. Would it be OK for you to already merge this version into master?

**Comment by hplato** [comment]
yes   is there anything I need to do?

**Comment by hollie** [comment]
No, merge is done. If you add other commits to this branch they should show up here for further merging.

Regards!
 Lieven.

**Comment by hplato** [comment]
Sounds good. Thanks Lieven.

**Pull request merged**
