### PR TITLE
Add Support for "Fast On" & "Fast Off"

### PR DESCRIPTION
**Pull request by DoumP**
Allow the state_now  command to recognise fast on and fast off command.

### CODE REVIEW

**Comment by DoumP** [comment]
For some reason your fix doesn't work for me, I'm still getting only on/off.
I'm far from mastering perl and so far I can't figure out why it's not working.
I can use the on_fast with a switchlinc so there's definitely a way to get that working with the remotelinc.

**Comment by marcmerlin** [comment]
@DoumP: What's the current status? Are you waiting for @krkeegan  to review your new patch which is now fully working for you?

**Comment by DoumP** [comment]
Yes is does work for me but I had to copy part of the code from the Dimmable_Device which doesn't seem optimal.

**Comment by gduprey** [comment]
Howdy,

So reading over the patch/code, I get the impression that this just "smerges" the on & on_fast and off & off_fast into on or off state.  Is there a way for user code to determine that an "on" was just an on vs an on_fast?

i.e. if  ($myLight->state_now eq "on_fast") { do something on a double click }

Gerry

**Comment by gac410** [comment]
I had an alternate implementation that I did ages ago, but it didn't
seem to generate any interest, due to the conflict between the light and
the switch state.

https://github.com/gac410/misterhouse/commit/81483280b78d843fd0d5f13d1f04385e967f4698

Rather than try to keep refitting it, I have stopped pulling, and I'm
stuck on the older code.  It works for me, and tbh I'd rather have the
double-click controls for things like overriding timers, etc., than the
current restrictions.

So to the powers that be.  Please make sure that we can get and process
the *_fast commands from devices like switchlinc-relay.  I'd rather not
maintain local patches.

Thanks,
George

**Comment by DoumP** [comment]
@gduprey : I've done this patch exactly to be able to use code as in your example.

**Comment by gduprey** [comment]
Sorry to keep dragging this on.  I'm up for applying the patch, but how do you write code to take advantage of a double tap/on_fast command?

Right now, I have ,pl code like if ($mylight->state_now eq 'on').  

With Georges patch, would I just use if ($mylight->state_now eq 'on_fast') ?

Thanks!

Gerry

**Comment by gac410** [comment]
I do things like:

Konsole output
if ( $state = ( state_now $l_bath_fan_lt ) ) {
    if ( $state eq 'on_fast' ) {
       set $bath_fan_timer (0);       #cancel the timer
..

and

Konsole output
if ( $state = ( state_now $l_kitchen_oh_s1 ) ) {
   if ( $state eq 'off_fast'  ) {
       set $undercounter     OFF;
       set $back_hall        OFF; 
       set $kitchen_recessed OFF;
    ...

George

**Comment by gduprey** [comment]
I looked int he code base and it appeared that there is already some logic for on_fast and off_fast.   The above path seemed to only be to enable that for the RELAY switch linc device too.  Is that correct (i.e. all other non-RELAY devices already support on/off_fast?)

Sorry -- trying to merge several different issues, threads and messages I'm finding on this topic and all seem slightly different.

Gerry

**Comment by DoumP** [comment]
I finally got it to work as krkeegan suggested.

**Comment by DoumP** [comment]
Yes Gerry, my goal was to get on_fast on the remotelinc.

**Comment by marcmerlin** [comment]
DoumP, so if I read it right, you were able to use this existing FastOn/FastOff code and his patch is not needed anymore?
If so, do you mind closing this request?

**Comment by gac410** [comment]
My patch referenced above - https://github.com/gac410/misterhouse/commit/81483280b78d843fd0d5f13d1f04385e967f4698   adds *_fast command support to the relay type devices.  I think that's different than the remote_link support.   I did a pull request ages ago that was rejected, so I just live with my local modifications.

**Comment by DoumP** [comment]
Marc, I have fixed my patch so it's now clean and simple.
I think it should be in MisterHouse, but if it's not appropriate I'll do like gac410 and live with my local modification.

**Comment by marcmerlin** [comment]
@DoumP the problem is that your tree is not up to date, maybe it wasn't a checkout of master?
Either way, see how it says "This branch has conflicts that must be resolved"
I'm happy to help merge, but can't merge this, it won't work.

**Comment by hollie** [comment]
This conflict is a result of the changes that were created by the perltidy pull request. Please see #566 on how to fix this.

Best regards,
 Lieven.

**Comment by DoumP** [comment]
It's not showing conflict anymore, I hope I did that the right way, if not I can just do a new pull request.

**Comment by marcmerlin** [comment]
something is off though
https://github.com/hollie/misterhouse/pull/478/files
shows me 0 files changed, 0 lines changed, i.e. you change seems empty

**Comment by DoumP** [comment]
I've created a new pull request https://github.com/hollie/misterhouse/pull/572

**Comment by hplato** [comment]
This has been superseded by a revised pull request.

**Pull request closed without merging**
