### PR TITLE
Added support for Insteon outlet

### PR DESCRIPTION
**Pull request by DaveNeudoerffer**
Added support for the Insteon outlet device 2663-222. Code in Insteon/Lighting.pm and record processing added to read_table_A.pl.

This device is a little different as it takes commands to group 1 and group 2. I modelled the code off the fanlinc device code, although I am pretty sure that code doesn't work. I don't have a fanlinc device so I didn't want to muck with it.

### CODE REVIEW

**Comment by hplato** [comment]
Is use Data::Dumper part of the standard MH libs? Maybe comment it out just to be safe?

**Comment by DaveNeudoerffer** [comment]
It didn't work without the 'use' -- maybe because it is in a class?

**Comment by hplato** [comment]
Sorry, I was wondering if we should embed the debug Data::Dumper in this lib.

Looks like I'm guilty of that as well in a bunch of my modules as well. Could be something that gets cleaned up at release time. 

Ecobee.pm:use Data::Dumper;
Nanoleaf_Aurora.pm:use Data::Dumper;
OpenSprinkler.pm:use Data::Dumper;
PLCBUS.pm:use Data::Dumper qw(Dumper);
Pushbullet.pm:use Data::Dumper;
Pushover.pm:use Data::Dumper;
Pushsafer.pm:use Data::Dumper;
RoomMe.pm:use Data::Dumper;
Venstar_Colortouch.pm:use Data::Dumper;
Wink.pm:use Data::Dumper;
Yeelight.pm:use Data::Dumper;
mqtt.pm:use Data::Dumper;
raZberry.pm:use Data::Dumper;

**Comment by DaveNeudoerffer** [comment]
Thanx.

Quick question:  are stacked pull requests in git valid?  I am new to git
-- the previous pull request was my first ever!  But I did submit a second
one I think even before you merged my first one.  Does that cause problems?

Dave

**Comment by hplato** [comment]
If the pull request is updated before merged, then yes those additional commits get bundled as part of the request. Normally not a problem. Generally when I scan through a pull request I look to see the scope of the change. For a specialized independant module that a contributor submits, they know their device and if there are problems they are contained to a small isolated part. Changing things like json_server.pl or http_server.pl needs a bit more scrutiny. The great thing about git is that if a pull request does mess something up, we can always find the commit and roll back or fix.

**Comment by DaveNeudoerffer** [comment]
Hi Howard,

Thanx for approving previous pull requests.  I had submitted a 3rd one
(#813) a few weeks ago.   I am not sure if there is something wrong with
it, or if I am supposed to do something else to get it going, or if it just
takes time.

Sorry to bug you.

Dave

**Pull request merged**
