### PR TITLE
Ia7 v1.1.200

### PR DESCRIPTION
**Pull request by hplato**
Updates to IA7 since the v4 stable freeze in the fall. I've been using this code for a few months without issue, however with the changes to http_server and ajax.pm be good to get some more testers. Plus master should be cutting edge!

Improvements include
- notifications. Banners and alert windows
- web audio, including changes to support safari http streaming. Mobile devices work as well (have to press the gear button as audio needs an action before playing on IOS).
- IP Address override. Allow for config_json settings per client IP (ie. can be used to set certain devices to default to web audio)
- Weather Station 2 will now show last RRD update time.

### CODE REVIEW

**Comment by hollie** [comment]
Hey Howard,

I tried merging this branch in my running system and for one reason or the other the web interface I had configured to suit my setup shows empty after the merge.

I haven't had time to look into this further in detail, but I wonder: did you change something in the way customizations can be applied that would cause the web interface not to shown any buttons? The heading and the 'checking' button are there, but that is all.

Kind regards,
 Lieven.

**Comment by hplato** [comment]
Whoa! That commit somehow has the more experimental v1.2 stuff in it. Yes there's a change to the authorization subsystem (it now actually works!), which adds a new collection id of 700 requirement. Clive found this and my latest update has fixed the issue, but i haven't pushed it yet. A workaround is adding a collection id 700 with 

"User" : "$Authorize"

(I think, i'm doing that from memory)

It would be great to test v1.1.200 as it has made some big changes. To http and ajax modules to support audio streaming, and is 4 months old or so. I've been using it on my production setup without issue. 

I'm also thinking about how this change can be applied against custom collection files.

**Comment by hplato** [comment]
Can I somehow pull that pull request back and submit another one with this commit from March 3rd?

https://github.com/hplato/misterhouse/commit/bf0645c903317d32df08bf41fe192f2717d82583

v1.2 is making things cleaner (full in-browser support for changing users, most of the ‘Setup Mr.House modules now work’, comics & mail are working, About Mr.House now has buttons to view the prefs files), however there are still some things to clean up for triggers and items. Probably a week or two and v1.2 would be ready to test.

On another note, do you think with the bsc.pl fix and the longer perltidy lines, the issues are fixed on stable?

Lastly, I would also vote for moving in mqtt into the next version. So far working well, with two things;

1. I see an uninitialized value on startup:

04/11/16 09:25:39 PM *** Keep Alive = 121
04/11/16 09:25:39 PM *** mqtt mqtt_connect Socket (127.0.0.1:1883,121) 
04/11/16 09:25:39 PM *** mqtt Socket check (121) [  ]: Connected
04/11/16 09:25:39 PM *** mqtt mqtt Received: ConnAck/at-most-once Connection Accepted 
04/11/16 09:25:39 PM *** mqtt mqtt Sub 1 Received: (--No $$msg{string}--)
04/11/16 09:25:39 PM *** mqtt mqtt Initializing MQTT connection ...
04/11/16 09:25:39 PM *** mqtt added MQTT check_for_data ...

04/11/16 09:25:39 PM Oops1: Use of uninitialized value in concatenation (.) or string at /usr/local/misterhouse/git-prod/bin/../lib/mqtt.pm line 682.

04/11/16 09:25:39 PM *** mqtt mqtt set mqtt: [(on), (mqtt=HASH(0x592b430)), ]

2. debug should be pulled from mh.ini (ie. remove line 198)

**Comment by hollie** [comment]
Hey Howard,

if you committed all changes to the same branch in your repo then it will not be that easy to revert. That is why you need to make a separate branch for different changes. This makes separating the pull requests easier.

On the other hand: I have no issue moving to v1.2 for testing immediately...

Best regards,
 Lieven.

**Pull request merged**
