### PR TITLE
Update POD to Indicate That poll_all Will Not Be Called on Code Reloads

### LINKED ISSUE #429: Insteon:  Should "Poll All" Occur During Code Reloads?
The <b>poll_all</b> subroutine in the Insteon <b>BaseInterface.pm</b> file states that it is run anytime MH is started or the code is reloaded; however, the current code only allows it to run if mh_exit is set to 'normal'.

During normal operations, mh_exit is set to 'abend' in order to detect if an unclean shutdown has occurred (on the next startup), so during a code reload the subroutine will always assume an abnormal exit has occurred and throw an error message instead of performing the polls.

As far as whether or not this <i>should</i> occur during a code reload, I am not sure, but I believe that according to the POD it is currently expected to run.

### PR DESCRIPTION
**Pull request by JaredF**
Fixes #429

### CODE REVIEW

**Comment by hollie** [comment]
Hey all,

it's been a while since there was activity on this pull request. It is not clear to me if this should be merged into master or not.

Can you please let me know if we should keep this open, or if we should merge it?

Thanks!
 Lieven.

**Comment by JaredF** [comment]
Hi @hollie, sorry, unfortunately it's been quite a while since I've had any real time for HA work...maybe it's because MH has been running so smoothly lately that I just haven't needed to ;)

I think the reason this was never merged is that there was a question over whether we should change the code to match the documentation or the documentation to match the code.  Both @krkeegan and @peloy gave good arguments as to why the documentation should be changed to match the current code behaviour and I am inclined to agree with their reasoning.

I will review the last version of this pull request and modify it if necessary to accomplish this.

**Comment by JaredF** [comment]
Okay; I think this one is finally ready to be merged.  The net change in the end is just to update the documentation to describe the existing behavior that everyone is already used to.

The back-and-forth shows as three separate commits; if you prefer me to squash these into a single commit, I can.

**Comment by hollie** [comment]
Hey @JaredF there is no need to merge the three commits into a single one. According to me part of the changes are already in master. If you look at https://github.com/hollie/misterhouse/pull/430/files there is only a small change in the comments that is not in master yet. 

So go ahead and merge this in!

**Pull request merged**
