### PR TITLE
Razberry 1.5.1 - support for zwave binary_sensor, and switch. Added in read_table_A support

### PR DESCRIPTION
**Pull request by hplato**

### CODE REVIEW

**Comment by hplato** [comment]
Does anyone know how to merge a branch that has conflicts? This commit should supercede the pervious updates to raZberry.pm

**Comment by tobser** [comment]
Merge the branch. Then on the conflicting files you can simply do 
git checkout --theirs PATH/FILE
to use the version from the other branch.

Tobi

**Comment by hplato** [comment]
How do I abandon this pull request, and send in a pull request for raZberry v1.6 that has the battery and digital blind support?

**Comment by hollie** [comment]
Hello Howard,

you can close this pull request like you did and then generate a new one just like you would do when creating a new pull request.

On the other hand: you can also update the branch where you originated this pull request from, and commit the changes. The new commits should automatically be added to this pull request.

Best regards,
 Lieven.

**Pull request closed without merging**
