### PR TITLE
Ia7

### PR DESCRIPTION
**Pull request by hplato**
Two fixes, an undefined error if a subpage is loaded without going to the IA7 root first. And a fix for the issue Dean Junk brought up "LONG_POLL when clicking on browse items & categories"

### CODE REVIEW

**Comment by hplato** [comment]
Dean tested this so I'm going to merge into master

**Comment by hplato** [comment]
Try updating from master to see if 1.4 fixed it, and if you use weather station 2, it will refresh data every minute (custom refresh rate can be set in ia7_config.json).

It doesn't use a long_poll, since reading the RRD multiple times a second put a large load on my development environment. Since by default the weather RRDs are updated every minute, a timed 60 second refresh minimizes the demands on the client and server.

**Comment by tobser** [comment]
I just pulled master and so far everything is working.

I do not use weather station, so I can't comment on that. But thanks for adding the other fix so quickly.

**Comment by hplato** [comment]
Thanks Tobi. I think the weather RRD is slick. I capture my internal temps, heating setpoints and solar radition. Interactive graphs!

**Comment by tobser** [comment]
Yep those RRD graphs look like a fun thing to have.. I really should free up some time to set those up...

**Comment by peloy** [comment]
Hi Howard,

Is there some documentation that covers the details of how to set this
up?

Cheers,

Eloy Paris.-

**Pull request merged**
