### PR TITLE
Json server fixes

### PR DESCRIPTION
**Pull request by waynieack**
Fix for rrd file path not being pulled from rrd_dir and weather_data_rrd ini params by default in json_server.pl. Also fixed an issue which can cause MH to crash.

### CODE REVIEW

**Comment by hollie** [comment]
Thanks for this pull request!

**Comment by hplato** [comment]
Since were changing the default weather RRD name, we should to check what name gets created on a fresh install.

I also thought it might be nice to have a JSON option to pass another rrd as an option. This could be useful for folks that have more than one RRD on their system

-        my $rrd_file = "weather.rrd";
 +        my $rrd_file = "weather_data.rrd";

**Comment by waynieack** [comment]
weather_data.rrd is the default on a new install with no config settings,
just tested with my dev system and weather_rrd_update.pl.

I left the json config setting that was already there as the last option so
it will override the mh.private.ini if its configured, is that what you
mean?



        my $rrd_file = "weather_data.rrd";
        $rrd_file = $config_parms{weather_data_rrd}
        if ( defined $config_parms{weather_data_rrd} );
        if ( $rrd_file =~ m/.*\/(.*\.rrd)/ ) {
             $rrd_file = $1;
            }
        $rrd_file = $json_data{'rrd_config'}->{'prefs'}->{'default_rrd'}
          if ( defined $json_data{'rrd_config'}->{'prefs'}->{'default_rrd'}
);


_Wayne

**Comment by hplato** [comment]
Perfect, thanks for checking that out.

I was thinking something like:

$rrd_file = $args{rrd_file}[0] if ( defined  $args{rrd_file}[0]  );

This would allow different sources to be graphed with a URL like this:

http://mh/ia7/#path=/rrd?now-6hour?indoor?rrd_file=doors.rrd

Of course, that’s just theory, I haven’t really tested this out yet as I just have one RRD source...

**Pull request merged**
