### PR TITLE
Only include the PLCBUS module if we actually need it.

### PR DESCRIPTION
**Pull request by hollie**
Otherwise we require users to install supporting modules for PLCBUS.

### CODE REVIEW

**Comment by hollie** [comment]
Hey @tobser 
is it OK if I change the line to 'require PLCBUS;'? This way the module is included at runtime when required.

I've already updated the fix_plcbus_module_requirement branch. Can you please test out and let me know if this is OK for you?

Best regards,
 Lieven.

**Comment by hollie** [comment]
See the fix here: #562

**Comment by tobser** [comment]
Hey Lieven,
your patch works fine. Thanks.

regads
Tobi

Am 22.11.2015 um 14:46 schrieb Lieven Hollevoet:

**Comment by hollie** [comment]
Hello Tobi,

thanks for testing. Merged!

Best regards,
 Lieven.

**Pull request merged**
