### PR TITLE
The inactivity timer wasn't working.  The on/off events from the time…

### PR DESCRIPTION
**Pull request by jduda**
…rs were getting confused with the on/off events from the Hawkey and security sensors.  I changed the logic to handle the events from the timers first, then the motion sensors.  Now the inactivity timers work properly.

### CODE REVIEW

**Comment by hollie** [comment]
Jim, I guess you want this in the next stable we're going to release in the next weeks, or do you want further testing and include this for v4.1?

Regards,
 Lieven.

**Comment by jduda** [comment]
Hi Lieven,

Yes please.  I did the push for the next stable.  The changes have been working well for me for a few weeks now.

Regards,

Jim

**Comment by marcmerlin** [comment]
I'm ok with merging, but "This branch has conflicts that must be resolved
￼Use the command line to resolve conflicts before continuing."
Could you resolve that bit?

**Comment by hollie** [comment]
Hey guys, 

I'm very sorry but currently I have zero bandwidth to work on this project. Earliest I could promise something is within 2 weeks...

Kind regards,
 Lieven.

**Comment by jduda** [comment]
I honestly don't know what I have to do to fix it.
Any advice?
I believe my forked branch was equal to the git hub when I did the pull request.

Regards,
Jim

**Comment by marcmerlin** [comment]
@hollie it looks like everyone sending pull requests has the same problem. Can you see what's going on?
@jduda without knowing more, I'd try to resync against master, re-apply your patch(es) and try again

**Comment by hollie** [comment]
The problem is that there were a few open pull requests at the time we merged the perltidy changes into master.

As the pull requests were created before the perltidy changes there are 2 pull requests changing the same file (the perltify one and this one). As a result git cannot determine what to do with the 2 changes to the same file and tells this by saying there are conflicts. 

The solution is indeed to bring the repo up to date with master, fix the conflicts and commit again. This should also update this pull request and make it mergeable.

**Comment by hollie** [comment]
Please see #566 to see on how to fix.

**Comment by hollie** [comment]
Hello @jduda can you please check if #581 has the changes you want to apply? I've ensured the merge conflicts are resolved. I'll close this pull request and if you agree with #581 I will merge it there.

**Pull request closed without merging**
