### PR TITLE
Razberry - Zwave Lock child object added

### PR DESCRIPTION
**Pull request by hplato**
Tested with a kwikset lock. Basic lock control and battery tracking. Advanced features such as pushing and deleting codes still a WIP.

### CODE REVIEW

**Comment by marcmerlin** [comment]
This branch has conflicts that must be resolved
￼Use the command line to resolve conflicts before continuing.

Could you solve these first so that we can look at a clean diff before merge?

**Comment by hplato** [comment]
I'll have the same issue as with venstar. I'm not a git expert so i'm unsure how to continue to contribute?

**Comment by marcmerlin** [comment]
Same comment here. Check out master, re-apply your patches, delete this pull request, and submit a new one.

**Comment by hplato** [comment]
OK, I’m in progress of updating my running with master and trying to figure out how to adapt a bunch of conflict files (those that I’ve modified, but with PerlTidy, the original file has changed so now I’ve got to figure out how to find the actual changes I’ve made, re-apply them against the ‘perltidy’d’ file, and then update.

Some short-term pain, but once we’re over this we’ll have a much cleaner codebase...

**Comment by hplato** [comment]
Can you look at the latest pull request. I did the following steps

- git checkout master
- git pull
- git checkout razberry
- cp lib/raZberry.pm /tmp
- git merge master
- cp lib/raZberry.pm /tmp
- perltidy -pro=../perltidyrc    #I downloaded this file from stable bin/.pertidyrc
- git add lib/raZberry
- git commit
- git push hplato

From what I see on the pull request, there is only one changed file, and it looks like only the lock changes. Can someone confirm?

**Comment by marcmerlin** [comment]
I didn't review the actual code, so I'm relying on you to have tested it, but otherwise it looks good. I'll merge.

**Pull request merged**
