### PR TITLE
Ia7 v1.3.560

### PR DESCRIPTION
**Pull request by hplato**
Bring the Scheduler UI and object logger components into master. The collections.json updater is now in a lib file, which doesn't require the user to enable a common code module for the authorization updates to apply. The common code module will need to be removed.

Also includes an older version of Wayne's schedule.pm, which should be updated with his revised version.

### CODE REVIEW

**Comment by hollie** [comment]
Hello Howard,

I'm trying this pull request out, and I was able to crash MisterHouse by clicking the buttons in the web interface. The thing is: I can't reproduce it reliably. Maybe a missing error/safety check?

I do have an error log:

```
Can't use string ("") as a HASH ref while "strict refs" in use at /Users/lieven/projects/mrhouse/master/bin/../lib/json_server.pl line 412.
 at mh line 31.
	main::__ANON__("Can't use string (\"\") as a HASH ref while \"strict refs\" in us"...) called at /Users/lieven/projects/mrhouse/master/bin/../lib/json_server.pl line 412
	main::json_get("GET", ARRAY(0x7fa942909c28), HASH(0x7fa941af5a20), undef) called at /Users/lieven/projects/mrhouse/master/bin/../lib/json_server.pl line 99
	main::json() called at /Users/lieven/projects/mrhouse/master/bin/../lib/http_server.pl line 544
	main::http_process_request(IO::Socket::INET=GLOB(0x7fa94239c670)) called at mh line 2745
	main::check_for_socket_data_http called at mh line 1821
	main::check_for_action called at mh line 4037
	main::monitor_commands called at mh line 8217
mh rc=1
-n mh had an unexpected exit
 ... sleep a bit, then restarting
```

**Comment by hplato** [comment]
Weird, if I look at line 412 on the v1.3.560 commit is in the RRD section

     $data{'last_update'} = $xml_info->{'last_update'} * 1000 if ( defined $xml_info->{'last_update'} );

I think this error is that there is a null reference in a hash. The above line doesn’t have a variable as a hash reference.

What were you doing when it happened? That line is close to the new object logger stuff. Maybe add a print line after "if ( $path[0] eq 'history') {“ so we can narrow down the area?

**Comment by hplato** [comment]
Were you able to reproduce the error?  I've been using the new code on my production setup for the past few weeks without any crashes.

**Comment by hollie** [comment]
Hello Howard,

no, I was not able to reproduce it. I'd not wait to merge this pull request.

Best regards,
 Lieven.

**Pull request merged**
