### PR TITLE
Venstar colortouch

### PR DESCRIPTION
**Pull request by hplato**
Confirmed what heating setpoints work.

### CODE REVIEW

**Comment by marcmerlin** [comment]
This branch has conflicts that must be resolved
Can you fix?

**Comment by hplato** [comment]
I don't know what that means. Maybe its the perltidy changes?

**Comment by marcmerlin** [comment]
pull master, rebase against it.

**Comment by hplato** [comment]
I did this for the original pull request;

$git checkout master
$git pull
$git checkout venstar_colortouch 
$cd lib
$cp /tmp/Venstar_Colortouch.pm .
$git add Venstar_Colortouch.pm 
$git commit
$git push hplato venstar_colortouch

So now, I did;

$git pull hplato master  (while on the venstar_colortouch branch)
From github.com:hplato/misterhouse
 * branch            master     -> FETCH_HEAD
Auto-merging lib/Venstar_Colortouch.pm
CONFLICT (content): Merge conflict in lib/Venstar_Colortouch.pm
Removing data/organizer/calendar.tab
Removing code/public/Brian/old stuff i don't use anymore/tracking.pl
Removing code/public/Brian/old stuff i don't use anymore/tk_widgets.pl
Removing code/public/Brian/old stuff i don't use anymore/tk_frames.pl
Removing code/public/Brian/old stuff i don't use anymore/radar.pl
Removing code/public/Brian/old stuff i don't use anymore/callog.pl
Removing code/public/Brian/old stuff i don't use anymore/calllog.pl
Removing code/bruce/outlook_programing.pl
Removing code/bruce/organizer_tasks.pl
Removing code/bruce/organizer_events.pl
Automatic merge failed; fix conflicts and then commit the result.

Can I just overwrite Venstar_Colortouch.pm with master, and then I’ll diff the changes and see what needs to be done? Or if this is due to perltidy, can I run that on my working copy somehow?

**Comment by marcmerlin** [comment]
Please don't remove Venstar_Colortouch.pm and replace it with yours. If it's changed, it's for a reason I'm sure. Look at what changed (manual diff) and apply your mods to the new version, then test carefully to make sure you didn't break anything, and submit the new patch.

**Comment by hplato** [comment]
I did a diff, and I’m pretty sure it’s the perltidy change.  I’m not sure of all the changes I made since perltidy was run on master. Lieven, what options did you use to run perltidy on the repository. I think if I run my local copy through perltidy with the same options, the ‘git diff’ should be more useful.

**Comment by hollie** [comment]
Hey Howard,

I used the ‘preludial’ script that is present in the master branch and that is documented here:
https://github.com/hollie/misterhouse/wiki/Contributing#using-perltidy-to-make-consistent-formatted-code <https://github.com/hollie/misterhouse/wiki/Contributing#using-perltidy-to-make-consistent-formatted-code>

Kind regards,
 Lieven.


> Op 5-jan.-2016, om 05:53 heeft hplato <notifications@github.com> het volgende geschreven:
> 
> I did a diff, and I’m pretty sure it’s the perltidy change. I’m not sure of all the changes I made since perltidy was run on master. Lieven, what options did you use to run perltidy on the repository. I think if I run my local copy through perltidy with the same options, the ‘git diff’ should be more useful.
> 
>

**Comment by marcmerlin** [comment]
@hollie can you assist?
I'm not following very closely, but it looks like master got reformatted and is causing problems for all patches now.
If so, could you manually pull in and merge @hplato 's 2 patches ?
Thanks.

**Comment by hplato** [comment]
Yup, thats what i ran against venstar_colortouch. On github it showed only the few changes i made to the file that would be merged in, hence my confusion

**Comment by hollie** [comment]
Hey guys,

I looked into this, and according to me the changes are ready to be merged. To be sure I have also created a new pull request that starts from the master and where I imported the file from the branch of @hplato. Both pull requests look identical to me ( #570 and #571 ). So feel free to select one of both to merge.

Regards,
 Lieven.

**Comment by hplato** [comment]
I'll type the merge request again. it only shows the 1 file changed for me.  I've pulled down master, I've merged master into my branch (says Already up to date), pushed it to git hub (Everything up to date), so It should merge just the one file? Can a second pair of eyes look?

**Comment by hollie** [comment]
Seems good to go for me!

**Pull request merged**
