### PR TITLE
Initial import of mqqt code from Neil

### PR DESCRIPTION
**Pull request by hollie**
Code was submitted on the mailing list. Moving it here so multiple people can work on the same codebase.

### CODE REVIEW

**Comment by hollie** [comment]
Input from Neil in the mail:

Right now the first design decision is that I'll use wild cards instead
of a socket for each device. We can map the topic into the device when
I get to that part. No ssl or tls is supported and no Websocket.

So you'll need to add this to the mh.private.ini:
```
       mqtt_host=test.mosquitto.org
       mqtt_server_port=1883
       mqtt_topic=home/#
       mqtt_user=user                  # (optional)
       mqtt_password=password          # (optional)
       mqtt_keepalive=120              # (optional)
```
You don't need the user or password as there's no code for it yet.

When you start up MH you will get a ton of data and I may have left
a Dumper or 2 in the code.

To test the mqtt, I send data from the command line:

mosquitto_pub -d -h test.mosquitto.org -q 0 -t home/ha/test/x10/A1 -m "A1AON"

I'm modeling my code after Jason Sharpee's UPB modules. I made a mistake
and didn't setup the mqtt.pm for multiple instances so I'm currently
back tracking to fix that. I'm also trying to figure out how the data gets
from the check_for_data function to the mh objects. I found this bit of
code in Jason's UPBPIM.pm (the interface pm, like the mqtt.pm):
```
   for my $obj (@{$$self{objects}}) {
	$obj->set($msg,$self);
   }
```
Which seems to say that I use the objects set method to do that work.

**Comment by hollie** [comment]
[copy of a message I sent on the mailing list, I think it is better to continue the discussion here].

Would it make sense to have an object that takes care of the connection to the MQTT server (kind of a gateway) and then have objects per instance that connect to the MQTT server through that gateway object.

I implemented such structure for the Squeezebox client interface:
https://github.com/hollie/misterhouse/blob/master/lib/SqueezeboxCLI.pm

What is your opinion on this?

**Comment by linuxha** [comment]
Actually the _server method does the same thing but I like the method SqueezeboxCLI.pm uses so I've switched over to it. I'll post that code later, I think I have the multiple subscriptions to the same host/port working now and I have some of the set partially working to and from mqtt. Lots and lots of print_logs going on so I can trace the flow. MH is maddeningly frustrating with examples that are understandable

**Comment by hollie** [comment]
Hey Neil,

feel free to push the changes to this branch on your clone, then everybody can easily access them and I can pull them in this branch.

**Comment by linuxha** [comment]
On 03/20/2015 02:54 AM, Lieven Hollevoet wrote:
> Hey Neil,
>
> feel free to push the changes to this branch on your clone, then everybody can easily
> access them and I can pull them in this branch.

I will in a couple of days (sorry) a bit busy at the moment. But I think
I have the mqtt to MH work us to the point where I can set the MH object
from Perl $mqtt_obj->set("On") or from the command line:


mosquitto_pub -d -h 127.0.0.1 -q 0 -t path/to/topic -m "Off"

That occurred at the last minute. I need to remove a lot of the
Data::Dumper code that's sitting there.

-- 
Linux Home Automation         Neil Cherry       ncherry@linuxha.com
http://www.linuxha.com/                         Main site
http://linuxha.blogspot.com/                    My HA Blog
Author of:    	Linux Smart Homes For Dummies

**Pull request merged**
