### PR TITLE
Fixed object declarations that were split over two lines as a result …

### PR DESCRIPTION
**Pull request by hplato**
…of Perltidy

### CODE REVIEW

**Comment by hollie** [comment]
Hey Howard, 

if OK for you I'd like to hold this merge until we're sure on if we actually want to manually fix files after a perltidy run. If we can fix the parser or the code then we might not need to manually intervent with code formatting anymore.

Best regards,
 Lieven.

**Comment by hollie** [comment]
Hello Howard,

what do you think, is this fixed already or should we still look into this?

Regards,
 Lieven.

**Comment by hplato** [comment]
If the travis CI has been working, let’s close this. Once master is updated and we’re testing 4.2, we can test some of the problematic common code modules (I think BSC was one of them)

**Comment by hollie** [comment]
Hello Howard,

Ok I agree with you. Closing this one and let's see where we get with testing on 4.2.

Thanks,
 Lieven.

**Pull request closed without merging**
