### PR TITLE
Hue emulation module for Misterhouse

### PR DESCRIPTION
**Pull request by waynieack**
This module has been tested with Google Home and the Amazon Echo. It should work for anything that supports the Hue bridge.

### CODE REVIEW

**Comment by hplato** [comment]
OK, Lieven, the CI stuff is great! It looks like there is a missing dependancy:

IO::Socket::Multicast

This brings up the whole site_libs vs loading separately, but I'm voting for keeping things encapsulated to make the install and setup as simple as possible. The Alexa stuff is a great compliment to homebridge, so IMHO it should work at startup. Wayne can you add in that dependancy and resubmit?

**Comment by waynieack** [comment]
I tried adding the module, but the test still fails. I am not sure whats going wrong with it.

**Comment by hplato** [comment]
I’m just out this weekend, but I’ll download a fresh master and see if I can replicate the travis result. Do you want to send in a pull request against my master?

**Comment by waynieack** [comment]
I just created the pull request.

_Wayne

**Comment by hplato** [comment]
Hey Wayne,

  Great!

  One more dependancy to add. CI dies on missing Net::Ethernet; 

Can't locate Net/Address/Ethernet.pm in @INC

Can you add that dependancy and update the pull request?

**Comment by hplato** [comment]
OK, one more (interesting, this one didn't show up when I installed IO::Socket::Multicast)

Can't locate Net/Ifconfig/Wrapper.pm in @INC

**Comment by hplato** [comment]
Looks good, no errors at startup!

**Comment by waynieack** [comment]
Net::Address::Ethernet is only used for discovering the local IP and can be manually defined in the mh.private.ini so I just did a eval on it and log the error below if its not defined. This way the user can install the module if they want to.

[Alexa] Error: Net::Address::Ethernet is not installed... Please install it or define the local IP and mac in alexaHttpIp/alexaMac

**Pull request merged**
