### PR TITLE
Opensprinkler

### PR DESCRIPTION
**Pull request by hplato**
Add in basic support for interfacing with the Opensprinkler device

### CODE REVIEW

**Comment by hollie** [comment]
Hey @hplato 
could it be that you accidentally added the same file twice? Or am I misinterpreting the overview under 'files changed'?

Best regards,
 Lieven.

**Comment by hplato** [comment]
Maybe?  I originally called it Opensprinkler.pm, but then renamed it to OpenSprinkler.pm to be more consistent with the product at a mid-point while testing with Brian

**Comment by hollie** [comment]
No, I mean the file that is under lib/OpenSprinkler.pm (= the correct one) and the file that is directly under the root of the repo (that one is probably incorrect)?

**Comment by hplato** [comment]
Yup, no idea why there is one on the root. Just the lib one

**Comment by hollie** [comment]
Hey @hplato,

if the file in the root is not required (as I assume it is), could you please in your branch remove the file, commit the change and push that change to your repo? Then the pull request gets updated and I can merge your change request easily.

To remove it, just do in the root of the clone (on the open sprinkler branch)

```
git rm OpenSprinkler.pm
git commit -m "Removed file that was added at the wrong location"
git puh origin opensprinkler
```

Thanks!
 Lieven.

**Comment by hollie** [comment]
By the way: you added the file in the root 3 weeks ago, in commit 084413050b2bd3ccdb9ad0d07617a9b8abd7b20c

**Comment by hplato** [comment]
Done!

**Comment by hollie** [comment]
Merged! Thanks for the contribution!

**Pull request merged**
