### PR TITLE
Alexa bridge Updates

### PR DESCRIPTION
**Pull request by waynieack**
Added the ability to respond with a state and level at the same time (from a sub) if needed. See Example below.

Fixed the response to a get when you use the custom mapped states with a sub. Before the fix, if the sub responded with the custom state it would not be mapped back to the on or off before it was sent to alexa.

The state sent from alexa (in a get request after alexa sends a set request) is used as the get response if it is not returned from a configured sub. This is so the get state request from alexa always matches what she set it to so she won't throw the malfunction error.

I use the state sent from alexa for the get request to an MH voice command to avoid the malfunction error. We don't do any state checks on an MH voice command.

We now respond with the full light definition during a discovery because the new Echo version doesn't like the short definition. This is ok now because the Echo now uses gzip compression so it does not limit the amount of supported devices

### CODE REVIEW

**Comment by waynieack** [comment]
I am not sure why all the old commits are listed or why its saying that WeatherNOAA.pm is different than the master version because they are the same....

**Comment by tobser** [comment]
i'm running you changes in my local system a couple of days now. Discovery and controlling devices works great again thanks for this fix. But i did not test your changes regarding the state and level sub, at the moment i only have on/off light devices configured...

**Comment by waynieack** [comment]
Awesome!

**Comment by waynieack** [comment]
I realized that the long discovery string with the older Alexa/Echo version that my Echos are running limits the number of devices to 20 (per chunk, so 20 x4) because the older Echo code does not use gzip compression for every discovery request. The latest commit only responds with the new longer string when gzip is supported which is a request from an Echo running the new code.  If you could grab the latest code and enable the debug and look for one of the following lines below. Also, add a new device and make sure that Alexa discovers it properly.  

11/20/19 09:55:50 PM [Alexa] Debug: Returning long format. Accept-Encoding=gzip

11/20/19 09:55:52 PM [Alexa] Debug: Returning short format. Accept-Encoding=

**Pull request merged**
