### PR TITLE
Create fallback directory, and populate it with MH-supplied versions …

### PR DESCRIPTION
**Pull request by bpmartin20**
…of CPAN modules from libe/site, so they can be overridden if desired.  This permits the sysadmin to install newer versions of modules from CPAN in the usual PERL library locations (e.g. /usr/local/lib/perl5), and have MH benefit from the updated code.  Prior to this change, the sysadmin would need to locally modify the distributed files (lib/site/LWP.pm, for example), which was essentially forking MH.

### CODE REVIEW

**Comment by hplato** [comment]
It would be great to wrap up the current master into a release and then add this — I think this is a great idea, but given the low activity on the project, things haven’t moved forward much. Given other commitments, I can’t package and communicate a release. 

Long way of saying, I agree with your approach, be nice to have a step release if anyone on the group can do it.

**Comment by marcmerlin** [comment]
@hplato  would it be ok to merge this without making a release (which is a lot more work, as you said)?
This ought to be in master to bake a little bit anyway.

**Comment by hplato** [comment]
Sure, let’s get the changes in so we can make a better next release! :)

**Comment by bpmartin20** [comment]
I wrote a long reply regarding testing and auto-switching, which I think 
has become obsolete in the time it took to write it.  We absolutely need 
to test this on more platforms than just mine.  MH has so many use-cases 
and so many different installation situations that I can't imagine 
trying to recreate anything near a reasonable test suite by myself.  
It's run for 11 or more months well for me, but that's not nearly enough 
to promise it will be solid for everyone everywhere.  If we can get it 
out to a wider test audience, that would be the way to go.

                           -Brian M.

**Comment by marcmerlin** [comment]
Ok, let's see how it goes. Please be around if people complain of issues :)

**Pull request merged**
